// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN4o7aB5uZM5YC4x0vAVoXp4NwR-ePctE',
    appId: '1:504333744886:android:682f9437ef8344691e0ad7',
    messagingSenderId: '504333744886',
    projectId: 'basr-flutter-project',
    databaseURL: 'https://basr-flutter-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'basr-flutter-project.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOcUY5d3TJukqaKaA6tm-mBBsuei8pDZY',
    appId: '1:504333744886:ios:08aaa26111ddd93b1e0ad7',
    messagingSenderId: '504333744886',
    projectId: 'basr-flutter-project',
    databaseURL: 'https://basr-flutter-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'basr-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.baseBloc3',
  );
}
